backend/smarttrip/src/main/java/com/group4/smarttrip/controllers/SmartItineraryController.java
backend/smarttrip/src/main/java/com/group4/smarttrip/services/GeminiService.java
backend/smarttrip/src/main/java/com/group4/smarttrip/services/ItineraryService.java
backend/smarttrip/src/main/java/com/group4/smarttrip/services/SmartItineraryService.java
backend/smarttrip/src/main/java/com/group4/smarttrip/services/ZoneService.java

feat: update smart itinerary algorithm

---

frontend/apps/web/package-lock.json
frontend/apps/web/package.json

config: update module packages

---

backend/smarttrip/src/main/java/com/group4/smarttrip/controllers/AuthController.java
backend/smarttrip/src/main/java/com/group4/smarttrip/services/AuthService.java
backend/smarttrip/src/main/resources/application.properties

feat: add google oauth service and controller

---

backend/smarttrip/src/main/java/com/group4/smarttrip/controllers/AuthController.java

fix: import oauth related class

---

backend/smarttrip/src/main/java/com/group4/smarttrip/config/SecurityConfig.java
backend/smarttrip/src/main/java/com/group4/smarttrip/controllers/AuthController.java
backend/smarttrip/src/main/resources/application.properties
frontend/apps/web/src/pages/Landingpage.tsx

fix: google auth redirect link

---

backend/smarttrip/src/main/java/com/group4/smarttrip/controllers/AuthController.java

fix: change redirect uri

---

frontend/apps/web/src/components/Layout.tsx
frontend/apps/web/src/components/PlaceCard.tsx
frontend/apps/web/src/pages/Landingpage.tsx

Fixed accidental redirection bug

---

frontend/apps/web/src/components/Layout.tsx

App mobile friendly v1

---

backend/smarttrip/src/main/java/com/group4/smarttrip/controllers/AuthController.java
frontend/apps/web/src/App.tsx

fix: redirect url link and duplicated import

---

frontend/apps/web/src/pages/Dashboard.tsx

Fix: Fixed redirection for smart trip

---

frontend/apps/web/src/components/Layout.tsx

Fixed bug where trip cards were not scrolling

---

backend/smarttrip/src/main/java/com/group4/smarttrip/services/BusynessService.java
backend/smarttrip/src/main/resources/application.properties

fix: update config to get ml-url through .env

---

frontend/apps/web/src/App.tsx
frontend/apps/web/src/pages/Dashboard.tsx
frontend/apps/web/src/pages/ExplorePlaces.tsx
frontend/apps/web/src/pages/Landingpage.tsx
frontend/apps/web/src/pages/MyItinerary.tsx
frontend/apps/web/src/pages/Oauth.tsx
frontend/apps/web/src/pages/SavedPlaces.tsx
frontend/apps/web/src/services/api.ts
frontend/apps/web/src/services/useItinerary.ts

fix: fix the token refresh flow

---

backend/smarttrip/src/main/java/com/group4/smarttrip/controllers/AuthController.java
frontend/apps/web/src/pages/Dashboard.tsx
frontend/apps/web/src/services/api.ts

fix: fix profile display new

---

backend/smarttrip/pom.xml
backend/smarttrip/src/main/java/com/group4/smarttrip/dtos/RegisterUserRequest.java

feat: add backend register user validation

---

backend/smarttrip/src/main/java/com/group4/smarttrip/controllers/BusynessController.java

debug: add more logs

---

backend/smarttrip/src/main/java/com/group4/smarttrip/controllers/BusynessController.java
frontend/apps/web/src/services/useItinerary.ts

Fix: busyness typo and useItinerary hook

---

frontend/apps/web/src/pages/MyItinerary.tsx

Fix: Fixed Mapapne

---

frontend/apps/web/src/components/Layout.tsx

Fix: fixed hero image

---

frontend/apps/web/src/pages/ExplorePlaces.tsx

Update ExplorePlaces.tsx Parenting busyness to the mappane

---

backend/flask-model-api/features_r.json

Update XGB prediction logic with GMM and bias correction

---

backend/smarttrip/src/test/java/com/group4/smarttrip/services/ItineraryServiceTest.java

fix: modify itinerary test

---

frontend/apps/web/src/services/useBusyness.ts

Fixed unknown busyness cache bug
